// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stargate.Server.Data;

#nullable disable

namespace Stargate.Server.Migrations
{
    [ExcludeFromCodeCoverage]
    [DbContext(typeof(StargateContext))]
    partial class StargateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Stargate.Server.Data.Models.AstronautDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CareerEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CareerStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentDutyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("AstronautDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerEndDate = new DateTime(1971, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CareerStartDate = new DateTime(1962, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "1LT",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            CareerStartDate = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Commander",
                            CurrentRank = "LTCOL",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            CareerStartDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Mission Specialist",
                            CurrentRank = "SPC4",
                            PersonId = 3
                        },
                        new
                        {
                            Id = 4,
                            CareerStartDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Command Pilot",
                            CurrentRank = "SGT",
                            PersonId = 4
                        },
                        new
                        {
                            Id = 5,
                            CareerEndDate = new DateTime(2011, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CareerStartDate = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "SPC2",
                            PersonId = 5
                        },
                        new
                        {
                            Id = 6,
                            CareerStartDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Pilot",
                            CurrentRank = "SPC4",
                            PersonId = 6
                        });
                });

            modelBuilder.Entity("Stargate.Server.Data.Models.AstronautDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DutyEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DutyStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DutyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("AstronautDuty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DutyEndDate = new DateTime(1962, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1962, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 1,
                            Rank = "SPC1"
                        },
                        new
                        {
                            Id = 2,
                            DutyEndDate = new DateTime(1964, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1963, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 1,
                            Rank = "SPC2"
                        },
                        new
                        {
                            Id = 3,
                            DutyEndDate = new DateTime(1966, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1965, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Pilot",
                            PersonId = 1,
                            Rank = "SGT"
                        },
                        new
                        {
                            Id = 4,
                            DutyEndDate = new DateTime(1967, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1967, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Commander",
                            PersonId = 1,
                            Rank = "2LT"
                        },
                        new
                        {
                            Id = 5,
                            DutyEndDate = new DateTime(1971, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1968, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Commander",
                            PersonId = 1,
                            Rank = "1LT"
                        },
                        new
                        {
                            Id = 6,
                            DutyStartDate = new DateTime(1971, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 1,
                            Rank = "1LT"
                        },
                        new
                        {
                            Id = 7,
                            DutyEndDate = new DateTime(2005, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Flight Engineer",
                            PersonId = 2,
                            Rank = "SPC2"
                        },
                        new
                        {
                            Id = 8,
                            DutyEndDate = new DateTime(2007, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2006, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Flight Engineer",
                            PersonId = 2,
                            Rank = "SPC4"
                        },
                        new
                        {
                            Id = 9,
                            DutyEndDate = new DateTime(2009, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2008, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Pilot",
                            PersonId = 2,
                            Rank = "SGT"
                        },
                        new
                        {
                            Id = 10,
                            DutyEndDate = new DateTime(2013, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Command Pilot",
                            PersonId = 2,
                            Rank = "MSGT"
                        },
                        new
                        {
                            Id = 11,
                            DutyEndDate = new DateTime(2015, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Commander",
                            PersonId = 2,
                            Rank = "2LT"
                        },
                        new
                        {
                            Id = 12,
                            DutyEndDate = new DateTime(2017, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Commander",
                            PersonId = 2,
                            Rank = "1LT"
                        },
                        new
                        {
                            Id = 13,
                            DutyEndDate = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Commander",
                            PersonId = 2,
                            Rank = "CAPT"
                        },
                        new
                        {
                            Id = 14,
                            DutyEndDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Commander",
                            PersonId = 2,
                            Rank = "MAJ"
                        },
                        new
                        {
                            Id = 15,
                            DutyStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Commander",
                            PersonId = 2,
                            Rank = "LTCOL"
                        },
                        new
                        {
                            Id = 16,
                            DutyEndDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 3,
                            Rank = "SPC2"
                        },
                        new
                        {
                            Id = 17,
                            DutyEndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 3,
                            Rank = "SPC3"
                        },
                        new
                        {
                            Id = 18,
                            DutyStartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 3,
                            Rank = "SPC4"
                        },
                        new
                        {
                            Id = 19,
                            DutyEndDate = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 4,
                            Rank = "SPC1"
                        },
                        new
                        {
                            Id = 20,
                            DutyEndDate = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 4,
                            Rank = "SPC3"
                        },
                        new
                        {
                            Id = 21,
                            DutyEndDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Pilot",
                            PersonId = 4,
                            Rank = "SPC4"
                        },
                        new
                        {
                            Id = 22,
                            DutyStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Command Pilot",
                            PersonId = 4,
                            Rank = "SGT"
                        },
                        new
                        {
                            Id = 23,
                            DutyEndDate = new DateTime(2009, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Flight Engineer",
                            PersonId = 5,
                            Rank = "SPC1"
                        },
                        new
                        {
                            Id = 24,
                            DutyEndDate = new DateTime(2011, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Flight Engineer",
                            PersonId = 5,
                            Rank = "SPC2"
                        },
                        new
                        {
                            Id = 25,
                            DutyStartDate = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 5,
                            Rank = "SPC2"
                        },
                        new
                        {
                            Id = 26,
                            DutyEndDate = new DateTime(2019, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 6,
                            Rank = "SPC1"
                        },
                        new
                        {
                            Id = 27,
                            DutyEndDate = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 6,
                            Rank = "SPC2"
                        },
                        new
                        {
                            Id = 28,
                            DutyStartDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Pilot",
                            PersonId = 6,
                            Rank = "SPC4"
                        });
                });

            modelBuilder.Entity("Stargate.Server.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Neil Armstrong"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Joseph Acaba"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Deniz Burnham"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zena Cardman"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Christopher Cassidy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Raja Chari"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dan Carson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dallas Davis"
                        });
                });

            modelBuilder.Entity("Stargate.Server.Data.Models.PersonAstronaut", b =>
                {
                    b.Property<DateTime?>("CareerEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CareerStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentDutyTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRank")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.ToTable("PersonAstronauts");
                });

            modelBuilder.Entity("Stargate.Server.Data.Models.AstronautDetail", b =>
                {
                    b.HasOne("Stargate.Server.Data.Models.Person", "Person")
                        .WithOne("AstronautDetail")
                        .HasForeignKey("Stargate.Server.Data.Models.AstronautDetail", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Stargate.Server.Data.Models.AstronautDuty", b =>
                {
                    b.HasOne("Stargate.Server.Data.Models.Person", "Person")
                        .WithMany("AstronautDuties")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Stargate.Server.Data.Models.Person", b =>
                {
                    b.Navigation("AstronautDetail");

                    b.Navigation("AstronautDuties");
                });
#pragma warning restore 612, 618
        }
    }
}
